### ISSUE TITLE
What is the purpose of `no-actor-in-scenario` ? 

### ISSUE THREAD

**Issue by remjx** [poenneby/eslint-plugin-codeceptjs#9]
Why would you want to prevent the usage of these methods within a Scenario()? What does it mean to prefer to "delegate to page objects"?

**Comment by poenneby** [comment]
Hi Mark. In some projects you may want follow the page object pattern. As your page evolve you only make changes in one place as opposed to changing the scenarios depending on this page.
In our scenarios we refer to page objects instead of the actor directly.
Hope this clarifies things?

**Comment by remjx** [comment]
Can you give an example? I don't understand how you can write a scenario without using any of these actors.

**Comment by poenneby** [comment]
You can read more about page objects in the codeceptjs documentation.
https://codecept.io/pageobjects

**Comment by remjx** [comment]
Got it: page objects, etc provide a level of abstraction to make the scenarios easier to read/write, so this rule forces you to write tests that way. Thanks!
